name: DEV CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Installation de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y

      # Installation des dépendances
      - name: Install dependencies
        run: |
          cd client
          docker-compose up --build --no-recreate -d



     